---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gvkdemoes.konveyor.openshift.io
spec:
  group: konveyor.openshift.io
  names:
    kind: GvkDemo
    listKind: GvkDemoList
    plural: gvkdemoes
    singular: gvkdemo
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: gvk-demo
---
apiVersion: konveyor.openshift.io/v1alpha1
kind: GvkDemo
metadata:
  name: gvk-demo
  namespace: gvk-demo
spec: {}

